# OpenVPN SERVER conf


# 安装 OpenVPN 服务端
# sudo apt-get update
# sudo apt-get install openvpn


# 生成HMAC SHA-1认证所需的ta.key文件
# openvpn --genkey --secret ta.key
 
# 生成服务器密钥和证书 
# apt-get install easy-rsa
# sudo find / -name easyrsa
# /usr/share/easy-rsa/easyrsa

# 这是新版本命令，老版本是 build-ca， pkitool，等等

###
## Please edit the vars script to reflect your configuration,
##  then source it with "source ./vars".
##  Next, to start with a fresh PKI configuration and to delete any
##  previous certificates and keys, run "./clean-all".
##  Finally, you can run this tool (pkitool) to build certificates/keys.
#
##
##  source ./vars
##  ./clean-all
##  ./build-dh     -> takes a long time, consider backgrounding
##  ./pkitool --initca
##  ./pkitool --server myserver
##  ./pkitool client1
##  ./pkitool --pass client2
##
##  
###

# easy-rsa init-pki
# easy-rsa build-ca
# easy-rsa build-server-full server nopass


# 复制证书和密钥
# cp -r /path/to/easy-rsa/pki /etc/openvpn


# 创建服务器配置文件
# vi /etc/openvpn/server.conf



port 1194
proto udp
dev tun

# 指定证书颁发机构（CA）的根证书文件
ca /etc/openvpn/keys/ca.crt

# 服务器证书文件
cert /etc/openvpn/keys/myserver.crt

# 服务器私钥文件。私钥与服务器证书配对使用来进行安全通信
key /etc/openvpn/keys/myserver.key

# Diffie-Hellman 参数文件
dh /etc/openvpn/keys/dh2048.pem

# 启用基于密钥的 TLS 认证，提供额外的保护层
tls-auth ta.key 0

topology subnet
server 10.8.0.0 255.255.255.0

# 指定 OpenVPN 服务器动态分配 IP 地址时记录分配情况的文件名
ifconfig-pool-persist ipp.txt

push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"
client-to-client
keepalive 10 120
comp-lzo
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status /var/log/openvpn-status.log
verb 3





# 配置防火墙 允许OpenVPN通信
sudo iptables -A INPUT -p udp --dport 1194 -j ACCEPT
sudo iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
sudo iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -j MASQUERADE




# 启动VPN服务
# sudo systemctl start openvpn@server
# sudo systemctl enable openvpn@server

sudo openvpn --config /path/to/server-or-client.config


