#      _   _____________   ___  __    __________  _   ________
#     / | / / ____/  _/ | / / |/ /   / ____/ __ \/ | / / ____/
#    /  |/ / / __ / //  |/ /|   /   / /   / / / /  |/ / /_
#   / /|  / /_/ // // /|  //   |   / /___/ /_/ / /|  / __/
#  /_/ |_/\____/___/_/ |_//_/|_|   \____/\____/_/ |_/_/
#
http {
    server {

        listen 80;

# 可以修改本地hosts指定域名
        server_name x.ai.com;

        #root /Users/zhaoq0103/DEV/source/Java-cloud/cloud-fliter/src/main/webapp;
        root /usr/share/nginx/html;

        access_log /var/log/nginx/webapp_access_log;
        error_log  /var/log/nginx/webapp_error_log;

        location /static {
        }

        location /favicon.ico {
        }

        location /WEB-INF {
            return 404;
        }

        location / {
#             proxy_pass       http://127.0.0.1:8080;
# 配置docker访问宿主机 host.docker.internal
            proxy_pass       http://host.docker.internal:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

events {
            worker_connections  1024;    #nginx的最大并发访问量
            use epoll;    #异步IO
}
